name: Swift

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-12
    steps:
      - uses: maxim-lobanov/setup-xcode@v1.4.1
        with:
          xcode-version: '13.3.1'

      - uses: actions/checkout@v3

      - name: Build
        run: swift build -v
      - name: Run tests
        run: swift test -v
